### PR TITLE
Support node relationships to other nodes of the same type in serialized.all

### PR DESCRIPTION
**Pull request by mprahl**
@yashvardhannanavati can you verify if this fixes your bug? If so, I'll clean up the code.

### CODE REVIEW

**Comment by yashvardhannanavati** [comment]
I tested this locally, the problem still persists :(

**Comment by mprahl** [comment]
@yashvardhannanavati can you push your branch so I can test against it?

**Comment by yashvardhannanavati** [comment]
Sure, actually the only change I made was remove the pdb and removing ".items()" from __all_properties__. Do you want me to overwrite on this branch?

**Comment by yashvardhannanavati** [comment]
ah, my bad. I think you mean the tests I wrote. I'll do it

**Comment by mprahl** [comment]
@yashvardhannanavati I fixed up the PR a bit. Try now.

**Comment by mprahl** [comment]
So I tried running your tests with a few minor tweaks with this code and it seems to work except that Python3 returns `parent` as a list of dictionaries instead of a single dictionary. I'll investigate tomorrow.

**Comment by mprahl** [comment]
@yashvardhannanavati cleaned up the PR. Could you review?

**Pull request merged**
